### ISSUE TITLE
Logging of tasks makes runner unbearably slow

### ISSUE THREAD

**Issue by badeball** [cypress-io/code-coverage#105]
Everytime code coverage is sent back to the node process (?), the stringified object is logged with its arguments, ref. https://github.com/cypress-io/code-coverage/blob/v1.10.2/support.js#L26. In my case, this is a 16839123-character long string and the rendering of this makes the runner unbearably slow.

Now, I realize that logging is a desired side-effect - maybe the logger itself should be able to cut obscenely large arguments?

In the meanwhile, I'm using [patch-package](https://github.com/ds300/patch-package) with the following patch.

```patch
diff --git a/node_modules/@cypress/code-coverage/support.js b/node_modules/@cypress/code-coverage/support.js
index 55b1e29..96ea722 100644
--- a/node_modules/@cypress/code-coverage/support.js
+++ b/node_modules/@cypress/code-coverage/support.js
@@ -23,7 +23,7 @@ if (Cypress.env('coverage') === false) {
       const applicationSourceCoverage = win.__coverage__
 
       if (applicationSourceCoverage) {
-        cy.task('combineCoverage', JSON.stringify(applicationSourceCoverage))
+        cy.task('combineCoverage', JSON.stringify(applicationSourceCoverage), { log: false })
       }
     })
   })
@@ -54,7 +54,7 @@ if (Cypress.env('coverage') === false) {
             // original failed request
             return
           }
-          cy.task('combineCoverage', JSON.stringify(coverage))
+          cy.task('combineCoverage', JSON.stringify(coverage), { log: false })
         })
     }
 

```

**Comment by bahmutov** [comment]
yeah, we can probably save logging time there
