### ISSUE TITLE
Ineffective configuration should error

### ISSUE THREAD

**Issue by jsphstls** [cypress-io/code-coverage#117]
When I successfully run tests while trying to set up code coverage I can see a report such as this:

```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

I clearly failed to properly configure my coverage collection but there is no indication of that failure.

These files are included in plugins:
```
  on('task', require('@cypress/code-coverage/task'))
  on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'))
```
This is in support:
```
import '@cypress/code-coverage/support'
```

Could any of these tools throw if they were used but coverage was never processed?

**Comment by bahmutov** [comment]
Yes, I am thinking I should show an error in the command log and add a link to this repo
