### ISSUE TITLE
CypressError: cy.task('coverageReport') failed 

### ISSUE THREAD

**Issue by samixchoumi** [cypress-io/code-coverage#155]
Hello,

I'm trying to launch coverage report on a docker container launching cypress.

As you can see below i've this error :
```
cypress   |   1 passing (2s)
cypress   |   1 failing
cypress   | 
cypress   |   1) Coverage_test "after all" hook: generateReport for "Test coverage":
cypress   |      CypressError: cy.task('coverageReport') failed with the following error:
cypress   | 
cypress   | > Error: Command failed with ENOENT: nyc report --report-dir ./coverage --temp-dir /.nyc_output --reporter=lcov --reporter=clover --reporter=json
cypress   | spawn nyc ENOENT
cypress   |     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
cypress   |     at onErrorNT (internal/child_process.js:456:16)
cypress   |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
cypress   | 
cypress   | 
cypress   | Because this error occurred during a 'after all' hook we are skipping all of the remaining tests.
```
My treefile looks like this : 

/node_modules
/cypress.json
/cypress
/.nyc_output
/package.json
/package-lock.json
/coverage

As you can see the file are at the root folder but it doesn't work and i run cypress by using npx.
Any idea on how to correct that, i'm looking on some solution but no one work for the moment.

**Comment by bahmutov** [comment]
What is the plugin's version, and what is your operating system? If the plugin is not the latest, could you try the latest version, please

**Comment by samixchoumi** [comment]
I use the latest version of docker cypress : **cypress/included:4.2.0**
I've found a solution but for me it's not normal to modify the dockerfile.
I've added this line : `ENV PATH "$PATH:./node_modules/.bin"`

**Comment by bahmutov** [comment]
Could you create a repo with exact setup and readme for me to run to see what you are doing, otherwise I would have to guess things

**Comment by drico** [comment]
> I use the latest version of docker cypress : **cypress/included:4.2.0**
> I've found a solution but for me it's not normal to modify the dockerfile.
> I've added this line : `ENV PATH "$PATH:./node_modules/.bin"`

Can you tell what solution you've found ? I'm in the same case.

**Comment by samixchoumi** [comment]
> > I use the latest version of docker cypress : **cypress/included:4.2.0**
> > I've found a solution but for me it's not normal to modify the dockerfile.
> > I've added this line : `ENV PATH "$PATH:./node_modules/.bin"`
> 
> Can you tell what solution you've found ? I'm in the same case.

As i say i added `ENV PATH "$PATH:./node_modules/.bin"` in the Dockerfile of the Cypress containers and it actually works.

**Comment by bahmutov** [comment]
I have added an example in this repo https://github.com/bahmutov/docker-with-cypress-included-code-coverage-example using `@cypress/code-coverage@2`, see if it works for you, please

**Comment by bahmutov** [comment]
Closing, since should be resolved
