### ISSUE TITLE
Configurable nyc 'relativeNycRunFromPath' parameter

### ISSUE THREAD

**Issue by alastair-todd** [cypress-io/code-coverage#160]
The tool has a locked opinion of where the cypress folder is in relation to the root of the project, typically:

`/cypress`

however we isolate cypress for e2e, thus

`/e2e/cypress`

so that it can have its own package.json

this means when nyc is called to generate the report it is from e2e, and not the source code root /

I've no idea the mechanics of that, but without running the command from root the report yields nothing (this is what cypress calls at test time)

`
C:\_dev\workspace\e2e\node_modules\.bin\nyc report --report-dir ./coverage --temp-dir C:\_dev\workspace\e2e\.nyc_output --reporter=lcov --reporter=clover --reporter=json
`

When manually run from `C:\_dev\workspace\e2e` = no report
When manually run from `C:\_dev\workspace\` = report

But its the former chosen by the tool and no apparent why to effect it.

**Describe the solution you'd like**
A configurable `relativeNycRunFromPath` parameter (for me that's `..`)

**Describe alternatives you've considered**
creating my own copy of task.js and updating process.cwd()

the change:
`return execa(foundNyc, args, { cwd: join(processWorkingDirectory, '..'),  stdio: 'inherit' })`

**Comment by bahmutov** [comment]
Hi @alastair-todd I have a beta release of Cypress that uses `nyc` as its own dependency and does not call it via `bin` folder. Could you try `@cypress/code-coverage@2.0.0-beta.1` and comment if it solves your problem?

**Comment by alastair-todd** [comment]
@bahmutov I updated everything and the issue persists. 

`nyc `is required to be run from the root of the source and in the scenario described above, it is one folder up (for me) than the default you have set in the plugin

i need to be able to change the `cwd ` of `execa `effectively

I perhaps think you interpreted this as the bin folder of `nyc`... not the folder it needs to run from

**Comment by alastair-todd** [comment]
I managed to find a workaround, using the named npm script referenced in task.js

`"coverage:report": "cd .. && e2e\\node_modules\\.bin\\nyc report --reporter=html --temp-dir=./e2e/.nyc_output --report-dir=./e2e/coverage"`
