### ISSUE TITLE
Coverage is not created if a spec fails

### ISSUE THREAD

**Issue by leorigon** [cypress-io/code-coverage#166]
**Coverage is not created if a spec fails**

**Versions**
`"@cypress/code-coverage": "2.0.0"`
`"cypress": "4.3.0"`
` ubuntu-16.04`
`v12.16.1` (node)
`6.13.4` (npm)

**Description**
If an scenario inside spec fails, the coverage is not generated, otherwise that coverage works fine. 
That error is emitted at console after tests run at all. 

```
Scenario x
    ✓ xxxxx (15850ms)
    1) "after each" hook for "xxxxxx"

  2) "after all" hook: collectBackendCoverage for "xxxxxx"

  1 passing (2m)
  2 failing

  1) Service order update "after each" hook for "xxxxxx":
     Error: Cypress command timeout of `15000ms` exceeded.

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at http://localhost:8081/__cypress/runner/cypress_runner.js:147599:25

  2) Service order update "after all" hook: collectBackendCoverage for xxxxxx":
     Error: Cypress command timeout of `15000ms` exceeded.

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
      at http://localhost:8081/__cypress/runner/cypress_runner.js:147599:25
```
We use cucumber with cypress running on azure pipeline, it's works if all specs passing, but our project is too big and we use cypress to help us to find bugs and improve the application.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example / repo? This is definitely not the case with other repos we test, so it's likely something specific to your setup that we'd need to identify. Thanks!

**Comment by leorigon** [comment]
@jennifer-shehane, thanks for your attention and help. 

I don't know if it makes sense, but in the above error, I was use the default electron  browser. When I changed it to chrome, that error doesn't occurred anymore. The coverage is generated correctly even for specs fails.
