### ISSUE TITLE
Add documentation on typescript (+webpack) support

### ISSUE THREAD

**Issue by ericorruption** [cypress-io/code-coverage#19]
My project is typescript + webpack based and I ran into some dead ends during setup because of that. Especially in the report generation part, `nyc` would always render an empty table even though the coverage file was there.

In the end I got the project running by using [`@istanbuljs/nyc-config-typescript`](https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript) and adding the suggested `.nycrc` file suggested in their documentation.

Hope it helps someone.

**Comment by jennifer-shehane** [comment]
@bahmutov suggestions?

**Comment by duncanhunter** [comment]
It would be great to have some documentation on this as I was unsuccessful getting coverage with typescript.

**Comment by selangley-wa** [comment]
Note that your documentation page:
https://docs.cypress.io/guides/tooling/typescript-support.html#Additional-information

suggests:

Additional information
See the excellent advice on setting Cypress using TypeScript in the TypeScript Deep Dive e-book by Basarat Syed.

We have published a utility npm module, add-typescript-to-cypress, that sets TypeScript test transpilation for you with a single command.

**Comment by SatorSquare** [comment]
I am also currently struggling with this. My code is instrumented and there is an out.json being generated in .nyc_output but the coverage report is a blank table as described above. I have tried the OPs suggestion to no avail. Documentation on how this is supposed to work with .ts and webpack would be excellent, as I am currently floundering.

**Comment by lluia** [comment]
I was having the same issue.

After some investigation, I got it working by installing also `babel-plugin-istanbul`, `@istanbuljs/nyc-config-typescript`:
```
yarn add -D \
  babel-plugin-istanbul \
  @istanbuljs/nyc-config-typescript \
  source-map-support \
  ts-node
```

Then in my `.babelrc`:
```js
// You want ONLY do this when building the app to be run by Cypress...
// A good approach is to control it through an environment variable:
// `if (process.env.CYPRESS_CODE_COVERAGE) plugins.push('istambul')`
plugins.push('istambul')
```
and on my `package.json`:
```json
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true
  },
```
( cc. @SatorSquare )

**Comment by lluia** [comment]
@jennifer-shehane I'm happy to open a PR adding documentation on how to get it working with TS 👍🏻

**Comment by bahmutov** [comment]
excellent @lluia this is good stuff, and I would love to have a small example repo we could clone and add it to the list here https://github.com/cypress-io/code-coverage#examples

**Comment by lluia** [comment]
@bahmutov I believe setting a **codesandbox** using `create-react-app` to illustrate the case should be fairly easy. I'll find some time this afternoon and post it here once ready 👍

**Comment by lluia** [comment]
@bahmutov as promised ❤️
https://github.com/lluia/cypress-typescript-code-coverage-typescript

**Comment by bahmutov** [comment]
Thank you @lluia I will refer others to your repo!

**Comment by maximgeerinck** [comment]
How would this work in create-react-app? I did overwrite the webpack config to add istanbul as a plugin. But it seems like that doesn't work. Any ideas on it?

**Comment by bahmutov** [comment]
right, @maximgeerinck - without ejecting you would need to somehow get your settings into webpack config
