### ISSUE TITLE
Support multiple spec files

### ISSUE THREAD

**Issue by ericorruption** [cypress-io/code-coverage#20]
Right now, the project generates code coverage for a single spec file. If multiple spec files exist, only the last one is available after all the tests run.

**Comment by bahmutov** [comment]
Do you mean when using "cypress open" and clicking on "Run all specs" button?

Are you sure - I just ran all specs in https://github.com/cypress-io/cypress-example-todomvc-redux to confirm and it is hitting 100% code coverage, while each individual spec hits only a subset. If you can give me a small reproducible repo that shows the problem ...

**Comment by ericorruption** [comment]
Thanks for the quick reply. I used `cypress run --browser chrome` to run my tests

**Comment by bahmutov** [comment]
yeah, see if you can give me a reproduction to see, but in general the coverage should be merged after each test, not overwrite it

**Comment by bahmutov** [comment]
yeah, I did it again in the example project using `cypress run --browser chrome` and still got full code coverage

**Comment by bahmutov** [comment]
I will close this for now, if there is a reproducible example, let me know and we will reopen

**Comment by ErikParso** [comment]
Hi, i have a same problem when running component tests `cypress run ct`. For each spec file it overrides in .nyc_output/out.json file and cobertura report file as well. In result I have a report for inly one spec file. Any suggestions?

in package.json

`	"nyc": {
		"reporter": [
			"cobertura", "lcov"
		]
	}`

in cypres plugin file i have

```
module.exports = (on, config) => {
	on('dev-server:start', (options) => {
		return startDevServer({
			options,
			webpackConfig,
		})
	});
	codeCoverageTask(on, config);
	return config;
};
```

**Comment by caioDelgado** [comment]
> Hi, i have a same problem when running component tests `cypress run ct`. For each spec file it overrides in .nyc_output/out.json file and cobertura report file as well. In result I have a report for inly one spec file. Any suggestions?
> 
> in package.json
> 
> ` "nyc": { "reporter": [ "cobertura", "lcov" ] }`
> 
> in cypres plugin file i have
> 
> ```
> module.exports = (on, config) => {
> 	on('dev-server:start', (options) => {
> 		return startDevServer({
> 			options,
> 			webpackConfig,
> 		})
> 	});
> 	codeCoverageTask(on, config);
> 	return config;
> };
> ```

hi, I have the same issue. Did you can fix it?
