### ISSUE TITLE
`cypress run` cannot output .nyc_output/out.json

### ISSUE THREAD

**Issue by z-pfei** [cypress-io/code-coverage#253]
"@cypress/code-coverage": "3.1.0",
"babel-plugin-istanbul": "6.0.0",
"cypress": "4.7.0",
"jest": "25.5.4"

cypress/support/index.js
```javascript
import '@cypress/code-coverage/support'
Cypress.Cookies.defaults({
    whitelist: () => {
        return true
    }
})
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from
    // failing the test
    return false
})
```

cypress/plugins
```javascript
module.exports = (on, config) => {
    require('@cypress/code-coverage/task')(on, config)
    on(
        'file:preprocessor',
        require('@cypress/code-coverage/use-browserify-istanbul')
    )
    return config
}
```

**Comment by bahmutov** [comment]
Please fill the full issue template https://github.com/cypress-io/code-coverage/blob/master/.github/ISSUE_TEMPLATE/bug_report.md, since we cannot determine the problem from the above information

You can get verbose logs following our https://github.com/cypress-io/code-coverage#debugging

**Comment by z-pfei** [comment]
@bahmutov Thanks for your reply, it's my personal issue.

**Comment by ravi-reactgeeks** [comment]
@z-pfei what was the issue? Could you share here? I am facing same issue
