### ISSUE TITLE
Parallel builds w/ code coverage fail (random test each time)

### ISSUE THREAD

**Issue by jhpedemonte** [cypress-io/code-coverage#276]
**Logs and screenshots**
Please provide debug logs by running Cypress from the terminal with `DEBUG=code-coverage` environment variable set, see the [Debugging](https://github.com/cypress-io/code-coverage#debugging) section of the README file.

See [comment below](https://github.com/cypress-io/code-coverage/issues/276#issuecomment-659533702)

**Versions**

- What is this plugin's version? If this is NOT the latest [released version](https://github.com/cypress-io/code-coverage/releases) can you try the latest version, please?

`"@cypress/code-coverage": "^3.8.1"`

- If the plugin worked before in version X, but stopped after upgrading to version Y, please try the [released versions](https://github.com/cypress-io/code-coverage/releases) between X and Y to see where the breaking change was.
- What is Cypress version?

`"cypress": "4.10.0"`

- What is your operating system?

Whatever linux version is in `cypress/included` Docker images.

- What is the shell?

`sh`

- What is the Node version?

`12.14.1` (Using Docker image `cypress-included:4.10.0`)

- What is the NPM version?

🤷 

- How do you instrument your application? Cypress [does not instrument web application code](https://github.com/cypress-io/code-coverage#instrument-your-application), so you need to do it yourself.

~~Use `craco` to customize `create-react-app`'s webpack config to add the `babel-plugin-instanbul` plugin. Similar to what is done by `instrument-cra`.~~

I am now using the latest `@cypress/instrument-cra` (v1.3.1) and still seeing this error.

- When running tests, if you open the web application in regular browser, and open DevTools, do you see `window.__coverage__` object? Can you paste a screenshot?
- Is there `.nyc_output` folder? Is there `.nyc_output/out.json` file. Is it empty? Can you paste at least part of it so we can see the keys and file paths?
- Do you have any custom NYC settings in `package.json` (`nyc` object) or in other [NYC config files](https://github.com/istanbuljs/nyc#configuration-files)

```
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "exclude": [
      "cypress/**",
      "**/__fixtures__/**",
      "**/__mocks__/**",
      "**/__tests__/**"
    ],
    "report-dir": "./coverage-cypress",
    "temp-dir": "./coverage-cypress/.nyc_output",
    "reporter": [
      "text-summary",
      "json",
      "html"
    ]
  }
```

- Do you run Cypress tests in a Docker container?

Yes, custom image based on `cypress-included:4.10.0`.

**Describe the bug**

I have a total of 113 Cypress tests. One random test (always just one, always different than before) will fail with an error like this:

```
      CypressError: `cy.task('coverageReport')` failed with the following error:
 
 > Unexpected end of JSON input
 
 Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
```

or 

```
      CypressError: `cy.task('coverageReport')` failed with the following error:
 
 > Unexpected string in JSON at position 1904650
 
 Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
```

**Update:** Seems to be related to parallel Cypress runs. Fairly consistently fails for me when running with parallelization, but succeeds when using a single (non-parallel) job.

**Comment by jhpedemonte** [comment]
I removed the `html` and `text-summary` and could not recreate error. Added back `html` and got error again.

Debug logs don't seem to be very helpful. Here's some snippets:

```
08:55:13    code-coverage coverage has 1466 record(s) +56ms
08:55:13  coverage has the following first paths
08:55:13  /app/client/src/utils/getBaseHrefFromDocument/getBaseHrefFromDocument.js
08:55:13  /app/client/src/utils/getBaseHrefFromDocument/index.js
08:55:13  /app/client/src/unsupportedBrowsers.js
08:55:13  /app/client/src/utils/URLBuilder/constants.js
08:55:13    code-coverage calling NYC reporter with options { 'report-dir': '/app/client/coverage-cypress', reporter: [ 'json', 'html' ], extension: [ '.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx' ], excludeAfterRemap: false, extends: '@istanbuljs/nyc-config-typescript', all: true, exclude: [ 'cypress/**', '**/__fixtures__/**', '**/__mocks__/**', '**/__tests__/**' ], 'temp-dir': './coverage-cypress/.nyc_output', reporterTODO: [ 'text-summary', 'json', 'html' ], tempDir: '/app/client/.nyc_output', reportDir: '/app/client/coverage-cypress' } +1s
08:55:13    code-coverage current working directory is /app/client +0ms
08:55:16    code-coverage after reporting, returning the report folder name /app/client/coverage-cypress +2s
08:55:16    code-coverage Final coverage in /app/client/coverage-cypress/coverage-final.json +0ms
08:55:16    1) "after all" hook: generateReport for "shows a message indicating you have no collections"
08:55:16  
08:55:16    2 passing (29s)
08:55:16    1 failing
08:55:16  
08:55:16    1) create enrichment
08:55:16         with no collections
08:55:16           "after all" hook: generateReport for "shows a message indicating you have no collections":
08:55:16       CypressError: `cy.task('coverageReport')` failed with the following error:
08:55:16  
08:55:16  > Unexpected token n in JSON at position 1889873
08:55:16  
08:55:16  Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
08:55:16        at http://localhost:4000/__cypress/runner/cypress_runner.js:158198:19
08:55:16        at tryCatcher (http://localhost:4000/__cypress/runner/cypress_runner.js:10130:23)
08:55:16        at Promise._settlePromiseFromHandler (http://localhost:4000/__cypress/runner/cypress_runner.js:8065:31)
08:55:16        at Promise._settlePromise (http://localhost:4000/__cypress/runner/cypress_runner.js:8122:18)
08:55:16        at Promise._settlePromise0 (http://localhost:4000/__cypress/runner/cypress_runner.js:8167:10)
08:55:16        at Promise._settlePromises (http://localhost:4000/__cypress/runner/cypress_runner.js:8243:18)
08:55:16        at _drainQueueStep (http://localhost:4000/__cypress/runner/cypress_runner.js:4837:12)
08:55:16        at _drainQueue (http://localhost:4000/__cypress/runner/cypress_runner.js:4830:9)
08:55:16        at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4846:5)
08:55:16        at Async.drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4716:14)
08:55:16    From Your Spec Code:
08:55:16        at Context.generateReport (http://localhost:4000/__cypress/tests?p=cypress/support/index.ts:953:8)
08:55:16    
08:55:16    From Node.js Internals:
08:55:16      SyntaxError: Unexpected token n in JSON at position 1889873
08:55:16          at JSON.parse (<anonymous>)
08:55:16          at maybePrintFinalCoverageFiles (/app/node_modules/@cypress/code-coverage/task.js:54:30)
08:55:16          at returnReportFolder (/app/node_modules/@cypress/code-coverage/task.js:200:7)
```

and

```
09:02:50    code-coverage coverage has 1466 record(s) +56ms
09:02:50  coverage has the following first paths
09:02:50  /app/client/src/utils/getBaseHrefFromDocument/getBaseHrefFromDocument.js
09:02:50  /app/client/src/utils/getBaseHrefFromDocument/index.js
09:02:50  /app/client/src/unsupportedBrowsers.js
09:02:50  /app/client/src/utils/URLBuilder/constants.js
09:02:50    code-coverage calling NYC reporter with options { 'report-dir': '/app/client/coverage-cypress', reporter: [ 'json', 'html' ], extension: [ '.js', '.cjs', '.mjs', '.ts', '.tsx', '.jsx' ], excludeAfterRemap: false, extends: '@istanbuljs/nyc-config-typescript', all: true, exclude: [ 'cypress/**', '**/__fixtures__/**', '**/__mocks__/**', '**/__tests__/**' ], 'temp-dir': './coverage-cypress/.nyc_output', reporterTODO: [ 'text-summary', 'json', 'html' ], tempDir: '/app/client/.nyc_output', reportDir: '/app/client/coverage-cypress' } +1s
09:02:50    code-coverage current working directory is /app/client +1ms
09:02:53    code-coverage after reporting, returning the report folder name /app/client/coverage-cypress +3s
09:02:53    code-coverage Final coverage in /app/client/coverage-cypress/coverage-final.json +0ms
09:02:53    1) "after all" hook: generateReport for "only shows the completed notification after all collections are done processing"
09:02:54  
09:02:54    1 passing (13s)
09:02:54    1 failing
09:02:54  
09:02:54    1) reprocessing collection
09:02:54         "after all" hook: generateReport for "only shows the completed notification after all collections are done processing":
09:02:54       CypressError: `cy.task('coverageReport')` failed with the following error:
09:02:54  
09:02:54  > Unexpected end of JSON input
09:02:54  
09:02:54  Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
09:02:54        at http://localhost:4000/__cypress/runner/cypress_runner.js:158198:19
09:02:54        at tryCatcher (http://localhost:4000/__cypress/runner/cypress_runner.js:10130:23)
09:02:54        at Promise._settlePromiseFromHandler (http://localhost:4000/__cypress/runner/cypress_runner.js:8065:31)
09:02:54        at Promise._settlePromise (http://localhost:4000/__cypress/runner/cypress_runner.js:8122:18)
09:02:54        at Promise._settlePromise0 (http://localhost:4000/__cypress/runner/cypress_runner.js:8167:10)
09:02:54        at Promise._settlePromises (http://localhost:4000/__cypress/runner/cypress_runner.js:8243:18)
09:02:54        at _drainQueueStep (http://localhost:4000/__cypress/runner/cypress_runner.js:4837:12)
09:02:54        at _drainQueue (http://localhost:4000/__cypress/runner/cypress_runner.js:4830:9)
09:02:54        at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4846:5)
09:02:54        at Async.drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4716:14)
09:02:54    From Your Spec Code:
09:02:54        at Context.generateReport (http://localhost:4000/__cypress/tests?p=cypress/support/index.ts:953:8)
09:02:54    
09:02:54    From Node.js Internals:
09:02:54      SyntaxError: Unexpected end of JSON input
09:02:54          at JSON.parse (<anonymous>)
09:02:54          at maybePrintFinalCoverageFiles (/app/node_modules/@cypress/code-coverage/task.js:54:30)
09:02:54          at returnReportFolder (/app/node_modules/@cypress/code-coverage/task.js:200:7)
```

**Comment by jhpedemonte** [comment]
From build with only `json` reporter set, I took the `coverage-final.json` and was able to use `nyc report` to successfully generate an HTML report.

**Comment by jhpedemonte** [comment]
I downloaded `coverage-final.json` for both failing and successful builds and tried to generate other reports like so:

`yarn nyc report --temp-dir temp --report-dir temp-report --reporter html`

(where `temp/` contains `coverage-final.json` and the output goes into `temp-report`)

But for both failure/successful builds, only an empty HTML file is outputted. So perhaps there's still something wrong with the `coverage-final.json` that is generated, even in successful builds?

As a point of comparison, the above `nyc` command works as expected for the `coverage-final.json` generated by `jest`.

**Comment by jhpedemonte** [comment]
I am no longer seeing this. May have been an issue in my configuration. Will reopen if I see it again.

**Comment by jhpedemonte** [comment]
Reopening. Started seeing this again.

```
   1) project delete
        "after all" hook: generateReport for "removes the project after deleted":
      CypressError: `cy.task('coverageReport')` failed with the following error:
 
 > Unexpected end of JSON input
 
 Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
       at http://localhost:4000/__cypress/runner/cypress_runner.js:158198:19
       at tryCatcher (http://localhost:4000/__cypress/runner/cypress_runner.js:10130:23)
       at Promise._settlePromiseFromHandler (http://localhost:4000/__cypress/runner/cypress_runner.js:8065:31)
       at Promise._settlePromise (http://localhost:4000/__cypress/runner/cypress_runner.js:8122:18)
       at Promise._settlePromise0 (http://localhost:4000/__cypress/runner/cypress_runner.js:8167:10)
       at Promise._settlePromises (http://localhost:4000/__cypress/runner/cypress_runner.js:8243:18)
       at _drainQueueStep (http://localhost:4000/__cypress/runner/cypress_runner.js:4837:12)
       at _drainQueue (http://localhost:4000/__cypress/runner/cypress_runner.js:4830:9)
       at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4846:5)
       at Async.drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:4716:14)
   From Your Spec Code:
       at Context.generateReport (http://localhost:4000/__cypress/tests?p=cypress/support/index.ts:953:8)
   
   From Node.js Internals:
     SyntaxError: Unexpected end of JSON input
         at JSON.parse (<anonymous>)
         at maybePrintFinalCoverageFiles (/app/node_modules/@cypress/code-coverage/task.js:54:30)
         at returnReportFolder (/app/node_modules/@cypress/code-coverage/task.js:200:7)
```

**Comment by jhpedemonte** [comment]
I have yet to see this issue when running locally (MacOS 10.15.6, Node.js 12.18.0).

**Comment by jhpedemonte** [comment]
Looks like this might be related to **parallel** builds. I have the CI set to run Cypress with 2 parallel jobs -- got 3 straight failures. But when I set to just 1 job, it worked twice in a row.

Someone else mentioned something along these lines, with similar error: https://github.com/cypress-io/code-coverage/issues/258

**Comment by jhpedemonte** [comment]
We figured it out: the issue was that we had each parallel instance of Cypress tests writing to the same code coverage directory. This would cause conflicts and errors as they each tried to read/write to the same files.

The correct way to handle this for parallel Cypress runs is to have each individual Cypress task write to a unique directory, then merge the reports into one final report using `nyc merge` or `nyc report`.

**Comment by panduka777** [comment]
@jhpedemonte How did you make individual cypress tasks write to unique directories?

**Comment by ImanMahmoudinasab** [comment]
> The correct way to handle this for parallel Cypress runs is to have each individual Cypress task write to a unique directory, then merge the reports into one final report using `nyc merge` or `nyc report`.

@jhpedemonte Can you please provide more details how you did it?

**Comment by jhpedemonte** [comment]
Simplified process is something like this:
1. We build a Docker image for our source and tests.
2. Run several instances of the Docker image in parallel. Requires using Cypress' [parallelization](https://docs.cypress.io/guides/guides/parallelization) feature or similar. A shared local directory is set as volume.
3. Inside the Docker image, coverage reports are written to the Docker's file system (for example, `coverage-cypress/coverage-final.json`).
4. Inside image, once tests are done, the coverage report is copied to the shared volume, with a unique name (i.e. `cp coverage-cypress/coverage-final.json shared-volume/coverage-cypress/from-cypress-${HOSTNAME}.json` where `HOSTNAME` is provided by Docker or docker-compose -- forget which).
5. After parallel tests are done, we then have unique files for each run. We run `nyc report --temp-dir shared-coverage-dir --report-dir coverage --reporter json --reporter html` to both merge and generate a report (where `shared-coverage-dir` contains the multiple `from-cypress-*.json` reports that were copied in step 4).

Unfortunately, there's a bug in `nyc` when doing merges; see https://github.com/istanbuljs/nyc/issues/1388. So final coverage reports will "fluctuate" until that is fixed.
