### ISSUE TITLE
Generated HTML has errors for some files (0% coverage even though showing non-zero items)

### ISSUE THREAD

**Issue by jhpedemonte** [cypress-io/code-coverage#279]
**Logs and screenshots**

![Screen Shot 2020-07-21 at 4 22 37 PM](https://user-images.githubusercontent.com/711365/88108464-7bad0880-cb6e-11ea-88bc-250373709c57.png)

![Screen Shot 2020-07-21 at 4 22 53 PM](https://user-images.githubusercontent.com/711365/88108466-7cde3580-cb6e-11ea-9c10-40f665bba074.png)

**Versions**

- What is this plugin's version? If this is NOT the latest [released version](https://github.com/cypress-io/code-coverage/releases) can you try the latest version, please?

`"@cypress/code-coverage": "^3.8.1"`

- If the plugin worked before in version X, but stopped after upgrading to version Y, please try the [released versions](https://github.com/cypress-io/code-coverage/releases) between X and Y to see where the breaking change was.
- What is Cypress version?

`"cypress": "4.10.0"`

- What is your operating system?

RHEL

- What is the shell?

`sh`

- What is the Node version?

`12.14.1` (Using Docker image `cypress-included:4.10.0`

- What is the NPM version?

🤷 

- How do you instrument your application? Cypress [does not instrument web application code](https://github.com/cypress-io/code-coverage#instrument-your-application), so you need to do it yourself.

Use `craco` to customize `create-react-app`'s webpack config to add the `babel-plugin-instanbul` plugin. Similar to what is done by `instrument-cra` but building instead of running in dev mode (similar to https://github.com/cypress-io/instrument-cra/issues/135#issuecomment-656164839).

- When running tests, if you open the web application in regular browser, and open DevTools, do you see `window.__coverage__` object? Can you paste a screenshot?
- Is there `.nyc_output` folder? Is there `.nyc_output/out.json` file. Is it empty? Can you paste at least part of it so we can see the keys and file paths?
- Do you have any custom NYC settings in `package.json` (`nyc` object) or in other [NYC config files](https://github.com/istanbuljs/nyc#configuration-files)

```
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "exclude": [
      "cypress/**",
      "**/__fixtures__/**",
      "**/__mocks__/**",
      "**/__tests__/**"
    ],
    "report-dir": "./coverage-cypress",
    "temp-dir": "./coverage-cypress/.nyc_output",
    "reporter": [
      "text-summary",
      "json",
      "html"
    ]
  }
```

- Do you run Cypress tests in a Docker container?

Yes, custom image based on `cypress-included:4.10.0`.

**Describe the bug**

After building an instrumented build and running Cypress tests, the generated HTML code coverage report shows some files with 0% coverage but actually having some non-zero covered code (see screenshots above).

When viewing one such file in the HTML report, it will show an error instead of file contents:

```
Cannot read property 'locations' of undefined
TypeError: Cannot read property 'locations' of undefined
    at /Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-reports/lib/html/annotator.js:127:50
    at Array.forEach ()
    at annotateBranches (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-reports/lib/html/annotator.js:125:33)
    at annotateSourceCode (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-reports/lib/html/annotator.js:233:9)
    at HtmlReport.onDetail (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-reports/lib/html/index.js:409:33)
    at Visitor.value (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at /Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-lib-report/lib/tree.js:92:19
    at Array.forEach ()
    at ReportNode.visit (/Users/pedemonte/projects/watson-discovery/discovery-tooling/node_modules/istanbul-lib-report/lib/tree.js:91:28)
```

**Comment by jhpedemonte** [comment]
Removing `"all": true` from the config makes this work better. Here are the same tests from the screenshot in description:

![Screen Shot 2020-07-21 at 5 27 29 PM](https://user-images.githubusercontent.com/711365/88113545-96d04600-cb77-11ea-9a95-891c4446c335.png)

But now this is missing a few files (like `CollectionMetadata`) which were in fact 0%.

**Comment by jhpedemonte** [comment]
I switched to building with latest `instrument-cra` (now that I can use it for `production` builds) and I no longer see this problem. Not sure why, since my `craco` config was doing basically same thing as `instrument-cra`. Closing.

**Comment by renaninacio** [comment]
I have same problem, where one file is not coverage, and his 0% coverage not impacts on final project coverage

![image](https://user-images.githubusercontent.com/50741708/93653481-80b3fa00-f9ef-11ea-840d-4dba61bde88a.png)

**Comment by cri-us** [comment]
Is there a any solution for this? @jhpedemonte  @inacior   same problem here, i tried to remove `"all": true` but its happens to some file missing, which i already use it inside `"include": [... , ...]` 
![Screenshot from 2022-06-28 16-13-18](https://user-images.githubusercontent.com/60355567/176187427-542f8da7-c34a-4bef-9c13-b9cff8b161a6.png)

**Comment by VendenIX** [comment]
is there any solution to this ?
