### ISSUE TITLE
Installing  @cypress/code-coverage 3.8.5 is unable to find @babel/* versions

### ISSUE THREAD

**Issue by jquintozamora** [cypress-io/code-coverage#348]
**Versions**
- What is this plugin's version? If this is NOT the latest [released version](https://github.com/cypress-io/code-coverage/releases) can you try the latest version, please? 
  3.8.5
- If the plugin worked before in version X, but stopped after upgrading to version Y, please try the [released versions](https://github.com/cypress-io/code-coverage/releases) between X and Y to see where the breaking change was.
- What is Cypress version?
6.0.0

**Describe the bug**
When I try to install the pkg using `yarn -D @babel/code-coverage` it is not able to find these versions:

Couldn't find any versions for "@babel/plugin-proposal-object-rest-spread" that matches "7.3.2"
Couldn't find any versions for "@babel/preset-env" that matches "7.4.5"
Couldn't find any versions for "@babel/core" that matches "7.4.5"
Couldn't find any versions for "@babel/runtime" that matches "7.3.1"

I think have to do with your dependency: "@cypress/browserify-preprocessor": "3.0.1"

**Comment by kachkaev** [comment]
Upstream issue: https://github.com/cypress-io/cypress-browserify-preprocessor/issues/59

**Comment by jquintozamora** [comment]
Sorry, Have to do with our internal registry, maybe if you use ^ we wouldn't have the issue.
