### ISSUE TITLE
Coverage not reported properly for untested pages with nextjs

### ISSUE THREAD

**Issue by AleksaC** [cypress-io/code-coverage#367]
**Versions**

- Plugin version `v3.8.8`
- `Cypress v6.1.0`
- `Ubuntu 20.04`
- `zsh`
- `node v12.18.2`
- `yarn 1.22.5`
- `babel-plugin-istanbul` instrumentation
- There is `window.__coverage__` and it only includes the current page and `_app.js`
- `.nyc_output` is present
- The nyc configuration can be seen in the repo provided bellow
- Ran on the host os

**Describe the bug**
The issue was originally discussed [here](https://github.com/bahmutov/next-and-cypress-example/issues/115).

Untested pages are shown as having 0 lines in coverage report. Additionally in my original repo it reports 404 page as having 100% coverage even though I'm not testing it, but I was not able to reproduce that with the repo I provided. 

Here is the report I get after running tests for the repo below:
```console
-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------|---------|----------|---------|---------|-------------------
All files  |     100 |      100 |     100 |     100 |                   
 pages     |     100 |      100 |     100 |     100 |                   
  404.js   |       0 |        0 |       0 |       0 |                   
  _app.js  |     100 |      100 |     100 |     100 |                   
  about.js |       0 |        0 |       0 |       0 |                   
  index.js |     100 |      100 |     100 |     100 |                   
 pages/api |       0 |        0 |       0 |       0 |                   
  hello.js |       0 |        0 |       0 |       0 |                   
-----------|---------|----------|---------|---------|-------------------
```

**Link to the repo**
Here's a [repo](https://github.com/AleksaC/nextjs-cypress-coverage-bug) reproducing the issue.

**Comment by bahmutov** [comment]
This is expected. When you tell Cypress coverage plugin that you are interested in all JS files, it finds all matching files and inserts zeroes into the coverage map. It does not instrument the source files (after all, this is for Next.js to do during bundling). Thus for pages that are not visited, the zeroes remain.

I would say if you want to "catch" any files that still have zero at the end, use https://github.com/bahmutov/check-code-coverage utilities or `nyc` itself to enforce minimum code coverage. The `check-code-coverage` for example would require the coverage to be above zero.
