### ISSUE TITLE
Web App is Not Instrumented Warning is being displayed Even for App with just Backend Code Coverage

### ISSUE THREAD

**Issue by mtapdilli** [cypress-io/code-coverage#372]
**Logs and screenshots**
![no-cov-info](https://user-images.githubusercontent.com/54978519/103685491-55134a80-4fb3-11eb-882f-930f66fecb00.PNG)

**Versions**

- What is this plugin's version?  **"@cypress/code-coverage": "^3.8.8"**
- What is Cypress version? - **"cypress": "^5.6.0"**
- What is your operating system? - **Windows**
- How do you instrument your application? Cypress [does not instrument web application code](https://github.com/cypress-io/code-coverage#instrument-your-application), so you need to do it yourself. - **"nyc": "nyc nodemon server.js"**
- When running tests, if you open the web application in regular browser, and open DevTools, do you see `window.__coverage__` object? Can you paste a screenshot? - **No. This application is just a backend app with express server.**

**Describe the bug** :
**Seeing the warning _[screenshot attached above]_ When executing the API tests [ For Express server ] using @cypress/code-coverage for code coverage. Report generation seems to be working fine. Raising the issue as requested by @bahmutov** 

![gleb-issue](https://user-images.githubusercontent.com/54978519/103686178-6e68c680-4fb4-11eb-916e-d6fe1e1df82c.PNG)

**Comment by bahmutov** [comment]
another example in https://github.com/bahmutov/todomvc-express-api-test-coverage
