### ISSUE TITLE
dayjs not present if used with Cypress < 6.8.0

### ISSUE THREAD

**Issue by dracos** [cypress-io/code-coverage#421]
Version 3.9.3 of this plugin does not work in versions of Cypress prior to 6.8.0, because (after https://github.com/cypress-io/code-coverage/pull/388) support.js imports dayjs which is not included in Cypress before then, and this plugin does not specify dayjs as a dependency itself, only a dev dependency. Cypress is given as a peer dependency, any version, and a dev dependency of 6.8.0.

Could dayjs be specified as a dependency, rather than a dev dependency? Thanks for your time, sorry if I have misunderstood something.

**Comment by bahmutov** [comment]
Let me check, definitely see that I added `dayjs` as dev dependency, but should have been a prod dependency

**Comment by bahmutov** [comment]
Yeah, in my testing, it accidentally used a dayjs dependency from Cypress itself, which is incorrect, for example

```
$ npm ls dayjs
cypress-example-todomvc-redux@1.0.0 /Users/gleb/git/cypress-example-todomvc-redux
└─┬ cypress@6.8.0
  └── dayjs@1.10.4 
```
