### ISSUE TITLE
incompatible with cypress@7

### ISSUE THREAD

**Issue by lianzhao** [cypress-io/code-coverage#424]
**Logs and screenshots**
![image](https://user-images.githubusercontent.com/536786/113652743-f1d6a880-96c6-11eb-98bf-7233cd6c6554.png)

**Versions**
`"@cypress/code-coverage": "^3.8.5"`

**Describe the bug**
`Cypress.moment` was [removed](https://docs.cypress.io/guides/references/changelog#7-0-0) in `Cypress@7`

**Comment by bahmutov** [comment]
We have released a version of this plugin that does not rely on `Cypress.moment`, see versions in https://github.com/cypress-io/code-coverage/releases and update to the latest
