### ISSUE TITLE
Show how to instrument and get code coverage for Angular application

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/code-coverage#51]
Would be nice to show an application scaffolded using https://nx.dev/angular/guides/modernize-cypress with TypeScript and code coverage from end-to-end tests

**Comment by skylock** [comment]
In the meantime where I can get the information how to implement this, I'am in exactly this situation, guidance is really appreciated !

**Comment by skylock** [comment]
Finally succeed !!! You can find here a [working example](https://github.com/skylock/cypress-angular-coverage-example)

**Comment by bahmutov** [comment]
nice, tried it locally and it works @skylock

**Comment by D0rmouse** [comment]
This this should be revisited, because @bahmutov implementations uses istanbul-instrumenter-loader, which isn't maintained and has a very old istanbul-lib-instrument dependency.

**Comment by D0rmouse** [comment]
This this should be revisited, because @bahmutov implementation uses istanbul-instrumenter-loader, which isn't maintained and has a very old istanbul-lib-instrument dependency.

Maybe there's some way to use babel-plugin-istanbul instead?

**Comment by skylock** [comment]
Can you point to an github repo with an working example ?

**Comment by D0rmouse** [comment]
See your [example repository issue](https://github.com/skylock/cypress-angular-coverage-example/issues/6) for details.

**Comment by Elif5757** [comment]
> Would be nice to show an application scaffolded using https://nx.dev/angular/guides/modernize-cypress with TypeScript and code coverage from end-to-end tests


the page shows 404 .. It doesn't work

**Comment by Elif5757** [comment]
> Finally succeed !!! You can find here a working example https://github.com/skylock/cypress-angular-coverage-example

@skylock it doesn't work with angular version 9.1.4

**Comment by LukasKlement** [comment]
@Elif5757 I made code coverage work with Angular 9, I wrote up a quick guide on it: https://lukas-klement.medium.com/implementing-code-coverage-with-angular-and-cypress-6ed08ed7e617

**Comment by MohamedSahir** [comment]
[LukasKlement](https://github.com/LukasKlement) can you update for angular 18 with code coverage facing issues https://github.com/cypress-io/code-coverage/issues/893
