### ISSUE TITLE
Broken in cypress 9.1

### ISSUE THREAD

**Issue by Narretz** [cypress-io/code-coverage#534]
I'm crossposting this issue from Cypress: https://github.com/cypress-io/cypress/issues/19070

I don't know where it needs to fixed, but I just want to bring it here to attention in case the fix should be made here.

**Comment by michaelhays** [comment]
Confirmed that this is also breaking for me.

This succeeds: `"@cypress/code-coverage": "^3.9.12"` + `"cypress": "9.0.0"`
This fails: `"@cypress/code-coverage": "^3.9.12"` + `"cypress": "9.1.0"`

Fails with the same message as the OP: `Unexpected token x in JSON at position ...`

**Comment by lmiller1990** [comment]
Seems this is fixed in Cypress 9.0.1 https://github.com/cypress-io/cypress/issues/19070#issuecomment-990744731
