### ISSUE TITLE
How do you keep the coverage tasks registered when using multiple config files?

### ISSUE THREAD

**Issue by gwvt** [cypress-io/code-coverage#563]
How do you keep the coverage tasks registered when using multiple config files as documented at https://docs.cypress.io/api/plugins/configuration-api#Customize-available-browsers?

In `plugins/index.js` as documented there:
```
module.exports = (on, config) => {
  const environment = config.env.configFile || "development";
  const configurationForEnvironment = fetchConfigurationByFile(environment);

  return configurationForEnvironment || config;
};
```
How do you incorporate
```
  require('@cypress/code-coverage/task')(on, config);
```
to register the coverage tasks on the returned config object? Config by file works but without coverage. Coverage works without config by file (i.e., just returning `config`). I can't get both to work together...

_Originally posted by @gwvt in https://github.com/cypress-io/code-coverage/issues/179#issuecomment-1120428049_

**Comment by suresh-raja-nxtgen** [comment]
Hi @gwvt , Were you able to solve this issue? I have the same problem

**Comment by gwvt** [comment]
Thank you @suresh-raja-nxtgen!

**Comment by jonnyeom** [comment]
@gwvt This doesnt seem to be working for me?

Is "codeCoverageTasksRegistered: true" same as calling the `registerCodeCoverageTasks` from `@cypress/code-coverage/task`?
