### ISSUE TITLE
combineCoverage timed out Unexpected

### ISSUE THREAD

**Issue by 42tg** [cypress-io/code-coverage#57]
Hi, im currently trying to extract the Coverage for my project with our Cypress tests.

We reside in an Typescript environment so first I suggested it is just a configuration fault. But after reworking our Webpack to clean things nicely up I get an nice Babel config for the files.

This works fine now and I get the `__coverage__` applied into my window object. And its filled fine by running through the test.

But after test execution in the `afterAll` step I get this error...
![image](https://user-images.githubusercontent.com/2226232/62295372-2d8a8b00-b46d-11e9-91fc-c89eb6c334e9.png)
```
CypressError: cy.task('combineCoverage') timed out after waiting 60000ms.

Because this error occurred during a 'after each' hook we are skipping all of the remaining tests.
```
![image](https://user-images.githubusercontent.com/2226232/62295420-4dba4a00-b46d-11e9-8106-ed85b2ad9128.png)

Even when I'm commenting out everything in `combineCoverage`  I still hanging there...

Any Ideas how to solve this?

**Comment by bahmutov** [comment]
Can you run Cypress with an environment variable set to see debugging messages, please? See https://github.com/cypress-io/code-coverage#debugging

**Comment by 42tg** [comment]
Ahh Nevermind,

sorry for bothering you. We implemented a feature lastly that you get asked via checkbox if you really wanna leave the page. This doesn't appear in `cypress open` and thats the reason why the `cy.window()` never return properly...

Sorry about that 😢

**Comment by bahmutov** [comment]
👍
