### ISSUE TITLE
Does not work with Create React App

### ISSUE THREAD

**Issue by piby180** [cypress-io/code-coverage#61]
Hey,

I have followed the official docs but yet unable to make it work with my react app. I use create-react-app utility and not webpack and babel.  It does create coverage and .nyc_output folder but no coverage is being calculated. 

> npx nyc report --reporter=text-summary

```
=========== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
==============================================================
```

**Comment by bahmutov** [comment]
It is lacking instrumentation, will show how to do it tomorrow

**Comment by 2manoj1** [comment]
Same issue we facing, latest nyc and "@cypress/code-coverage": "^1.8.0".

**Comment by filame** [comment]
I have a simular issue with React and @cypress/code-coverage.
I don't know if my issue is the one described above.

In my case nyc exports `.nyc_output/out.json` and the json file is **not** empty.
But the generated reporst looks like the one of @piby180.

**Comment by filame** [comment]
I got around that.
Since `.nyc_output/out.json` is not empty I now use `nyc report` to build the coverage html.

In my .nycrc.json I set `"reporters": ["json"]` so cypress only produces JSON coverage files.  
I also had to set `"extension: [".ts", ".tsx"]"` since I use Typescript (found in [this issue](https://github.com/istanbuljs/nyc/issues/1122)).

**Comment by bahmutov** [comment]
You can use https://github.com/cypress-io/instrument-cra to instrument CRA v3 apps without ejecting the scripts

**Comment by judsoncarver** [comment]
Using `instrument-cra` now with our Typescript CRA app (created with create-react-app --typescript), and I see we have a `window.__coverage__` in console, listing all of our tsx files we'd expect. Cypress (also configured to use TS) is set up per the code-coverage docs (I see the expected tasks before and after each test run, and .nyc/out.json is populating as expected.)

Still getting empty coverage results on test runs, though: `----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|`

Is there a guide to setting up instrument-cra with typescript apps and getting results?

**Comment by bahmutov** [comment]
@piby180 do you still need help with CRA v3 app?

**Comment by judsoncarver** [comment]
@bahmutov Been using instrument-cra with a typescript CRA-based app, and implemented code-coverage as outlined in the cypress/code-coverage docs. Still getting blank coverage, despite our app showing as instrumented. Any docs or guidance on implementing for a typescript CRA app (cypress itself is still javascript in our repo, just the app is TS)?

**Comment by bahmutov** [comment]
@judsoncarver See a couple of TypeScript examples linked in https://github.com/cypress-io/code-coverage#examples Since TS files are NOT automatically included in the report, you need to add NYC settings like https://github.com/lluia/cypress-typescript-coverage-example/blob/master/package.json#L13 I think

```
"nyc": {
  "extends": "@istanbuljs/nyc-config-typescript",
  "all": true
}
```
