### ISSUE TITLE
Empty e2e coverage results

### ISSUE THREAD

**Issue by smitch88** [cypress-io/code-coverage#65]
Hey,

I'm noticing some weird coverage behavior with an instrumented front-end react app and an instrumented e2e set of specs. I've verified the counters across both front-end and spec code.

* Showing the end result of `combineCoverage`
<img width="423" alt="Screen Shot 2019-08-18 at 12 05 00 AM" src="https://user-images.githubusercontent.com/762107/63219980-3ad19600-c14c-11e9-9998-6c208201bb73.png">

#### Debugging efforts
I rewrote `combineCoverage` to print out a global summary and I get the following 2 results,

* The first call to `combineCoverage` seems to show the proper result
<img width="577" alt="Screen Shot 2019-08-18 at 12 05 26 AM" src="https://user-images.githubusercontent.com/762107/63219977-37d6a580-c14c-11e9-9fb9-b79c88a52268.png">

* The second call which basically passes in an empty coverage map seems to break everything and produce an empty result.
<img width="546" alt="Screen Shot 2019-08-18 at 12 05 32 AM" src="https://user-images.githubusercontent.com/762107/63219976-34431e80-c14c-11e9-87a5-b813f3d04a5f.png">
 
#### Conclusion
Is there some weird behavior with the merge with empty maps happening [here in this code](https://github.com/cypress-io/code-coverage/blob/master/task.js#L70)? 

It could also be that this should not be running that last `combineCoverage` in the `After` lifecycle and Im not sure why its running there in the first place.

**Comment by smitch88** [comment]
Downgraded from `"nyc": "^14.1.1",` and things started working properly

**Comment by ManuBoca92** [comment]
I am also receiving an empty coverage result when I run my e2e tests. I followed the guidelines step by step. I have also tried downgrading nyc to 13.x.x and even 12.x.x but the issue still persists.

**Comment by ManuBoca92** [comment]
I have tried downgrading `nyc` to both `13.x.x` and `12.x.x`.  I have the following packages `"istanbul-lib-coverage": "^2.0.5"`,  `"@cypress/code-coverage": "^1.10.1"`. Maybe` nyc 13.x.x`. works with a particular version of these packages?

**Comment by Farhanklenty** [comment]
i have same configuration and it is working for mine.
Are you instumented your code before running the test cases.that is the requirement.'
i have instumented using  "nyc instrument" and the i am running my test case on instrumented code using "@cypress/code-coverage",i m combining code coverage and using nyc i am generating report.

**Comment by ManuBoca92** [comment]
Aha! no I did not instrumented it, thanks.

**Comment by ShamansCoding** [comment]
> Yes ,There is issue with nyc 14.1.1 just downgrade to 13.x.x it should work

Downgraded to version 13.3.0, it's working now.

**Comment by bahmutov** [comment]
ok, I will close this for now, since it is not clear that this is a problem in `@cypress/code-coverage` but more of the `nyc` problem
