### ISSUE TITLE
Missing moment dependency 

### ISSUE THREAD

**Issue by lribac** [cypress-io/code-coverage#664]
Really interested in using this tool but haven't been able to get pass the `moment` dependency issue. Some posts suggest that the new versions should be using `dayjs` but I still get the `moment` usage in the latest version. Have also tried using older versions but still getting the issue every time. 

**Logs and screenshots**
<img width="721" alt="Screenshot 2023-06-14 at 2 29 44 PM" src="https://github.com/cypress-io/code-coverage/assets/36741317/fdb578bb-8589-40ce-af8f-64d8fc523dc5">

**Versions**
code-coverage version: `3.10.7`
Cypress version: `12.14.0`

**Comment by mike-plummer** [comment]
Hi @lribac , sorry you're having issues. From the path in the error (`.../@cypress/react/node_modules/@cypress/code-coverage/support.js`) it looks like your project is attempting to use a version of `@cypress/code-coverage` that's a transitive dependency (which happens to be an older version). Can you confirm a couple things?

1. Your project has `@cypress/code-coverage` as a direct dev dependency (listed in your `package.json`?
2. Your `cypress.config.js` file imports from that direct dependency via `require('@cypress/code-coverage/task')(on, config)`
3. Your support file imports from the direct dependency `import '@cypress/code-coverage/support'`

If those are all valid, can you share your project or a minimal reproduction case?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by lribac** [comment]
The issue was using [cypress/react](https://www.npmjs.com/package/@cypress/react?activeTab=readme) outdated dependency. Upgrading to the latest version solved it. Thank you!

**Comment by mike-plummer** [comment]
Thanks for circling back with a resolution @lribac , glad you got it resolved. Thanks for using Cypress!
