### ISSUE TITLE
task "combineCoverage" times out for big projects

### ISSUE THREAD

**Issue by jidma** [cypress-io/code-coverage#76]
I have a project with 424 instrumented source files.

The task "combineCoverage" allways runs into a timeout (even after waiting for 2h30).

![cypress1](https://user-images.githubusercontent.com/2295247/65054038-74204000-d95c-11e9-9d87-d313619b707e.jpg)

**After some digging:**

I added some debug in the following code:

https://github.com/cypress-io/code-coverage/blob/40a602d4b26a22b28ced552e7829a27f38a2cebc/support.js#L17-L29

- I found out that my `win.__coverage__` contains a huge object (with 424 entries) that serializes to a 7.5MB string.

- The `combineCoverage `task is never reached (I added a debug at the beginning and it never prints).

- I created an empty task `testTask` which I called using the same object as parameter and it also got stuck.

- when I only instrument 3 files, it works fine.

**my workaround**

As a workaround, I'm currently 'splitting' my coverage object into smaller chunks (50 entries each). And it works fine. 

```javascript
  afterEach(() => {
    // save coverage after each test
    // because the entire "window" object is about
    // to be recycled by Cypress before next test
    cy.window().then(win => {
      // if application code has been instrumented, the app iframe "window" has an object
      const applicationSourceCoverage = win.__coverage__

      if (applicationSourceCoverage) {
        let i = 0;
        let tmpObj = {};
        Object.keys(applicationSourceCoverage).forEach(key => {
          let value = applicationSourceCoverage[key];
          tmpObj[key] = value;
          if (++i % 50 == 0) {
            cy.log(i + ' - ' + JSON.stringify(tmpObj).length);
            cy.task('combineCoverage', tmpObj)
            tmpObj = {};
          }
        });
        if (tmpObj !== {}) {
          cy.log(i + ' - ' + JSON.stringify(tmpObj).length);
          cy.task('combineCoverage', tmpObj)
        }
      }
    })
  })
```

it works fine as a temporary woraround:

![cypress2](https://user-images.githubusercontent.com/2295247/65054204-ba759f00-d95c-11e9-9262-32a8107b9b35.jpg)

**Comment by 42tg** [comment]
This is possibly the same as #26 
wich can be solved by [stringify](https://github.com/cypress-io/code-coverage/issues/26#issuecomment-526211185) the JSON before handing them to the node enviroment.

After that dont forget to parse it back to json before mergin it with the previous result.

**Comment by lynchem** [comment]
We're getting this problem as well. Can you clarify a little on what you're suggesting @42tg ?

**Comment by 42tg** [comment]
Hi take a Look here
https://github.com/cypress-io/code-coverage/issues/26#issuecomment-526211185
For my Post on the other issue. 

And for an concrete Implementation the referenced commit wich should solve your issue. 

https://github.com/SoftwareHeritage/swh-web/commit/00c006df690dea42b2ef02a763b41a11b559cabc

**Comment by lynchem** [comment]
Thanks for that. I was able to follow that commit and get ours working much quicker now as well.
