### ISSUE TITLE
Cross-origin not working

### ISSUE THREAD

**Issue by xxluke** [cypress-io/code-coverage#782]
**Logs and screenshots**
> #### SecurityError
> Failed to read a named property 'coverage' from 'Window': Blocked a frame with origin "http://localhost:4200" from accessing a cross-origin frame.

![grafik](https://github.com/cypress-io/code-coverage/assets/8194761/39f57be1-ecb6-40a7-9539-6de98df44b03)

**Describe the bug**
This extension causes an error when you visit a different origin, for example an external login-website, due to CORS. Since the external website doesn't offer coverage anyway, it wouldn't be necessary to fetch it.

There's already #685 which fixes this, unfortunally there seems to be no one willing or able to write a test for it so it can get merged.

If someone knows a work-around for this bug I'd be happy to hear about it. I tried `Cypress.on('uncaught:exception', ...)` but it seems not to get triggered by this error.

**Versions**
cypress-io/code-coverage 3.12.24
Cypress 13.6.2

**Comment by JRSalica** [comment]
I have exactly the same issue, did you find a fix or a workaround? thx!

**Comment by xxluke** [comment]
I haven't unfortunally. We're now writing more unit tests instead of Cypress for the coverage.
