### ISSUE TITLE
.nycrc doesn't set report-dir and reporter options

### ISSUE THREAD

**Issue by bondarenko09** [cypress-io/code-coverage#93]
I have `.nycrc` file with some configuration:
```json
{
  "extends": "@istanbuljs/nyc-config-typescript",
  "all": true,
  "check-coverage": false,
  "report-dir": "cypress-coverage",
  "reporter": [
    "text",
    "json"
  ]
}
```
The problem is neither `report-dir` nor `reporter` options works, until I set up this configs into my `package.json`

**Comment by rfftrifork** [comment]
Seems that I have the same problem, mine seems to ignore `.nycrc.json`. For me it seems as a anti-pattern even having such configs in `package.json`

**Comment by bahmutov** [comment]
I need to read JSON config files from https://github.com/istanbuljs/nyc#configuration-files

Right now we only read `nyc` from `package.json`, but should read and merge 

- `nyc` package.json
- `.nycrc` (JSON)
- `.nycrc.json`
